//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cruder.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cruder.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; and &apos;{1}&apos; fields didn&apos;t match..
        /// </summary>
        public static string Common_FieldsNotMatch {
            get {
                return ResourceManager.GetString("Common.FieldsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record has been found for given parameter..
        /// </summary>
        public static string Common_RecordNotFound {
            get {
                return ResourceManager.GetString("Common.RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same record with value of &apos;{0}&apos; already exist in database..
        /// </summary>
        public static string Core_Repository_ExistRecordMessage {
            get {
                return ResourceManager.GetString("Core.Repository.ExistRecordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cannot access this page with your current account access level !.
        /// </summary>
        public static string Web_Mvc_Controller_CruderAccountController_AccessLevelMessage {
            get {
                return ResourceManager.GetString("Web.Mvc.Controller.CruderAccountController.AccessLevelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You attempted wrong username and password combination 5 times. In 20 minutes your login request will be blocked..
        /// </summary>
        public static string Web_Mvc_Controller_CruderAccountController_FiveTimesAttemptMessage {
            get {
                return ResourceManager.GetString("Web.Mvc.Controller.CruderAccountController.FiveTimesAttemptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Web_Mvc_Controller_CruderAccountController_Login {
            get {
                return ResourceManager.GetString("Web.Mvc.Controller.CruderAccountController.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Web_Mvc_Controller_CruderAccountController_Password {
            get {
                return ResourceManager.GetString("Web.Mvc.Controller.CruderAccountController.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string Web_Mvc_Controller_CruderAccountController_RememberMe {
            get {
                return ResourceManager.GetString("Web.Mvc.Controller.CruderAccountController.RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Web_Mvc_Controller_CruderAccountController_Reset {
            get {
                return ResourceManager.GetString("Web.Mvc.Controller.CruderAccountController.Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Web_Mvc_Controller_CruderAccountController_Username {
            get {
                return ResourceManager.GetString("Web.Mvc.Controller.CruderAccountController.Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username and password combination!.
        /// </summary>
        public static string Web_Mvc_Controller_CruderAccountController_WrongCombination {
            get {
                return ResourceManager.GetString("Web.Mvc.Controller.CruderAccountController.WrongCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record has been created successfully..
        /// </summary>
        public static string Web_Mvc_Controller_CruderWebController_CreatedSuccessfully {
            get {
                return ResourceManager.GetString("Web.Mvc.Controller.CruderWebController.CreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record has been deleted successfully..
        /// </summary>
        public static string Web_Mvc_Controller_CruderWebController_DeletedSuccessfully {
            get {
                return ResourceManager.GetString("Web.Mvc.Controller.CruderWebController.DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record has been updated successfully..
        /// </summary>
        public static string Web_Mvc_Controller_CruderWebController_UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("Web.Mvc.Controller.CruderWebController.UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that code.
        /// </summary>
        public static string Web_ViewModel_MessageModel_ErrorCodeExtensionContent {
            get {
                return ResourceManager.GetString("Web.ViewModel.MessageModel.ErrorCodeExtensionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while your request was being processed..
        /// </summary>
        public static string Web_ViewModel_MessageModel_ErrorContent {
            get {
                return ResourceManager.GetString("Web.ViewModel.MessageModel.ErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error details.
        /// </summary>
        public static string Web_ViewModel_MessageModel_ErrorDetailsContent {
            get {
                return ResourceManager.GetString("Web.ViewModel.MessageModel.ErrorDetailsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string Web_ViewModel_MessageModel_FailureTitle {
            get {
                return ResourceManager.GetString("Web.ViewModel.MessageModel.FailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Web_ViewModel_MessageModel_InformationTitle {
            get {
                return ResourceManager.GetString("Web.ViewModel.MessageModel.InformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been processed successfully..
        /// </summary>
        public static string Web_ViewModel_MessageModel_SuccessfullyContent {
            get {
                return ResourceManager.GetString("Web.ViewModel.MessageModel.SuccessfullyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully.
        /// </summary>
        public static string Web_ViewModel_MessageModel_SuccessTitle {
            get {
                return ResourceManager.GetString("Web.ViewModel.MessageModel.SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Web_ViewModel_MessageModel_WarningTitle {
            get {
                return ResourceManager.GetString("Web.ViewModel.MessageModel.WarningTitle", resourceCulture);
            }
        }
    }
}
